
INCLUDE(util)

MESSAGE(STATUS "Configuring UNIX specific things and stuff...")

ADD_DEFINITIONS(-DSCP_UNIX)
ADD_DEFINITIONS(-DUSE_OPENAL)

FIND_PACKAGE(OpenGL REQUIRED)
FIND_PACKAGE(OpenAL REQUIRED)

SET(PLATFORM_INCLUDES ${PLATFORM_INCLUDES} ${OPENGL_INCLUDE_DIR} ${OPENAL_INCLUDE_DIR})
SET(PLATFORM_LBRARIES ${PLATFORM_LBRARIES} ${OPENGL_LIBRARY} ${OPENAL_LIBRARY})

IF(APPLE)
	include(platform-mac)
ELSE(APPLE)
	SET(EXE_GUI_TYPE)
ENDIF(APPLE)

